version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: health_platform_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: health_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: auth_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./services/auth-service:/app
      - ./shared:/app/shared
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/health_platform
      SECRET_KEY: your-secret-key-change-this-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      db:
        condition: service_healthy

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    container_name: user_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./services/user-service:/app
      - ./shared:/app/shared
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/health_platform
      SECRET_KEY: your-secret-key-change-this-in-production
    depends_on:
      db:
        condition: service_healthy

  health-data-service:
    build:
      context: .
      dockerfile: services/health-data-service/Dockerfile
    container_name: health_data_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload
    volumes:
      - ./services/health-data-service:/app
      - ./shared:/app/shared
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/health_platform
      SECRET_KEY: your-secret-key-change-this-in-production
    depends_on:
      db:
        condition: service_healthy

  ai-service:
    build:
      context: .
      dockerfile: services/ai-service/Dockerfile
    container_name: ai_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload
    volumes:
      - ./services/ai-service:/app
      - ./shared:/app/shared
    ports:
      - "8004:8004"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/health_platform
      SECRET_KEY: your-secret-key-change-this-in-production
      AUTH_SERVICE_URL: http://auth-service:8001
      USER_SERVICE_URL: http://user-service:8002
      HEALTH_DATA_SERVICE_URL: http://health-data-service:8003
    depends_on:
      - db
      - auth-service
      - user-service
      - health-data-service

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: api_gateway
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/api-gateway:/app
      - ./shared:/app/shared
    ports:
      - "8000:8000"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8001
      USER_SERVICE_URL: http://user-service:8002
      HEALTH_DATA_SERVICE_URL: http://health-data-service:8003
      AI_SERVICE_URL: http://ai-service:8004
    depends_on:
      - auth-service
      - user-service
      - health-data-service
      - ai-service

volumes:
  postgres_data:


